#!/usr/bin/ksh
###############################################################
###                                                         ###
###         buildusagereport                                ###
###                                                         ###
### Purpose:  ksh script to generate a listing of the sas   ###
###           directories by user for file system usage     ###
###           monitoring.  This script should be executed   ###
###           by root to prevent user attempts to hide      ###
###           files from succeeding.                        ###
### Author:   Samuel T. Croker                              ###
### Create:   5/21/09                                       ###
###############################################################

/sas/sas92/SASFoundation/9.2/utilities/bin/cleanwork /sas/saswork > /sas/adminscripts/cleanworkreport.txt 2>&1
ls -Alt /sas/saswork > /sas/adminscripts/workreport.txt
ls -RAlt /sas/saswork > /sas/adminscripts/fullworkreport.txt
ls -RAlt /sas/apps/sas_prod/ >  /sas/adminscripts/prodreport.txt
ls -RAlt /sas/datamart_data/ >  /sas/adminscripts/datareport.txt
ls -RAlt /home/ |grep -i sas >  /sas/adminscripts/homereport.txt
chown sasadmin:sasadmin /sas/adminscripts/*.txt
