#!/usr/bin/perl
#####################################################################################
#####  resetUserDirPerms
#####  author:  Samuel T. Croker
#####  Created: 7/30/09
#####  Purpose: This program renders the process of making a user directory readable
#####		into one command.  The reason is that I want to make this easy when
#####		the admin needs to see what is in a user's directory for disk space
#####		or if looking for a file.  The individual file permissions are 
#####		preserved, but the containing directory is made readable.
#####		THIS DOES NOT HANDLE SUBDIRECTORIES!   
#####  ARGS:    Command line arguments:
#####		ARGV[0] - userid of owner
#####		ARGV[1] - directory 
#####  I/O:	OUT: none 
#####		IN:  none
#####  Exec:    
#####
#####################################################################################

$loginname=getlogin();
if($loginname eq sasadmin){
	system "sudo chown -R sasadmin $ARGV[1]";
	system "chmod -R g+x $ARGV[1]";
	system "chmod  g+r $ARGV[1]";
	system "chmod -R g+rx $ARGV[1]/sasuser*";
	system "chmod -R g+rx $ARGV[1]/oldconfig";
	system "chmod  g+x $ARGV[1]/oldconfig"; 
	system "sudo chown -R $ARGV[0] $ARGV[1]";
}
else{
	print "Please log in as sasadmin before attempting to run this script";
}

